### ISSUE TITLE
Add description for custom mappings in Telescope which-key help

### ISSUE THREAD

**Issue by mksoc** [molecule-man/telescope-menufacture#13]
Hello, thanks for the great plugin, it's a perfect addition for my needs. Just a question: is it possible to add a description field for the keymaps defined by menufacture when the Telescope which-key help menu is shown? Right now it shows `<anonymous>` for al of them like in the picture:

![image](https://github.com/molecule-man/telescope-menufacture/assets/27402195/ecc6ea7a-f82f-44bc-b980-e7d38288c19d)

**Comment by molecule-man** [comment]
Hello,

Thanks, good idea :+1: . Added the descriptions to mappings:
![2024-03-16_09-30-01_302x39](https://github.com/molecule-man/telescope-menufacture/assets/1415116/0fb4f6a6-ac2e-4d51-a68e-82bb2e6360ef)

If it works for you as well then please close the issue.

**Comment by molecule-man** [comment]
Yep, should appear automatically after updating the plugins. I think I know what's the problem. There is this fix in telescope https://github.com/nvim-telescope/telescope.nvim/pull/2892. But the problem is that it's not released yet. Unfortunately this fix is required for the descriptions to appear. So the only option is to use master branch of telescope until the fix is released.

**Comment by mksoc** [comment]
Thanks, using master it works. I'd rather stick to a specific tag for now, but this is not urgent. Anyway this can be closed, thank you very much!
