### ISSUE TITLE
Picker custom keybindings don't work with telescope-menufacture

### ISSUE THREAD

**Issue by Jendker** [molecule-man/telescope-menufacture#6]
Hello,

I have added custom mappings for pickers:
```
local telescope = require('telescope')
local actions = require('telescope.actions')
telescope.setup({
  pickers = {
    live_grep = {
      mappings = {
        i = {
          ["<C-Down>"] = function(...)
            return actions.cycle_history_next(...)
          end,
          ["<C-Up>"] = function(...)
            return actions.cycle_history_prev(...)
          end,
          ["<C-f>"] = function(...)
            return actions.preview_scrolling_down(...)
          end,
          ["<C-b>"] = function(...)
            return actions.preview_scrolling_up(...)
          end,
          ["<c-r>"] = actions.to_fuzzy_refine,
        },
      },
    },
  }
})
```
Unfortunately if I call telescope-menufacture: `  "<cmd>lua require('telescope').extensions.menufacture.live_grep()<cr>"` then the defined keybindings such as `<c-r>` don't work. These keybindings work fine if I call the usual `"<cmd>lua require('telescope.builtin').live_grep()<cr>"`. Is there a way to mitigate that?

**Comment by molecule-man** [comment]
@Jendker thanks for reporting this

this plugin uses `attach_mappings`  behind the scenes and as it turned out telescope converts those mappings provided in the config also into `attach_mappings`: https://github.com/nvim-telescope/telescope.nvim/blob/47c755d737702df7a39b640c8d9c473a728be1df/lua/telescope/builtin/init.lua#L535-L544. Effectively `attach_mappings` if provided in `opts` completely overwrite `attach_mappings` derived from config. I don't know if it's intended or it's a bug in telescope - I'll create issue there. 

In the meantime I suggest to move the mappings from the setup to the `opts.attach_mappings` (**Please note: you need to load the latest version of this extension for this to work.**):
```lua
require('telescope').extensions.menufacture.live_grep {
    attach_mappings = function(_, map)
      local actions = require 'telescope.actions'
      map({ 'i' }, '<C-Down>', actions.cycle_history_next)
      map({ 'i' }, '<C-Up>', actions.cycle_history_prev)
      map({ 'i' }, '<C-f>', actions.preview_scrolling_down)
      map({ 'i' }, '<C-b>', actions.preview_scrolling_up)
      map({ 'i' }, '<C-r>', actions.to_fuzzy_refine)
      return true
    end,
}
```

I know this might be inconvenient but unfortunately I can't suggest better option as of now.

**Comment by Jendker** [comment]
Thank you for looking into this! That's a good workaround for now :) Could you link the telescope issue when possible?

**Comment by molecule-man** [comment]
> Thank you for looking into this! That's a good workaround for now :) Could you link the telescope issue when possible?

Yep, here it is https://github.com/nvim-telescope/telescope.nvim/issues/2612

**Comment by Jendker** [comment]
This was a lightning-speed fix! https://github.com/nvim-telescope/telescope.nvim/pull/2613 resolved the issue. Thank you so much and enjoy your day!
